package com.docker.app.entities.enums;

public enum Setores {
    ADMINISTRATIVO,
    VENDAS,
    GERENCIA,
    ESTOQUE,
    RECEPCAO,
    TI,
    FINANCEIRO,
    RH,
    MARKETING,
    COMPRAS,
    LOGISTICA,
    PRODUCAO,
    QUALIDADE,
    MANUTENCAO,
    JURIDICO,
    SUPRIMENTOS,
    ATENDIMENTO,
    PLANEJAMENTO,
    TELEATENDIMENTO,
    POS_VENDA,
    OPERACOES,
    DESENVOLVIMENTO,
    PESQUISA_DESENVOLVIMENTO,
    RELACIONAMENTO_CLIENTE,
    SEGURANCA_DO_TRABALHO;
}

