package com.docker.app.entities.enums;

public enum TipoChamado {
    INSTALACAO,
    MANUTENCAO_PREVENTIVA,
    MANUTENCAO_CORRETIVA,
    INSPECAO,
    TROCA_DE_COMPONENTE,
    ATUALIZACAO_SOFTWARE,
    CONFIGURACAO,
    TREINAMENTO,
    SUPORTE_REMOTO,
    SUPORTE_PRESENCIAL,
    TESTE,
    AUDITORIA,
    VERIFICACAO_DE_SEGURANCA,
    CALIBRACAO,
    LIMPEZA,
    REPARO,
    CONSULTORIA,
    MIGRACAO,
    SUBSTITUICAO,
    OTIMIZACAO,
    INCIDENTE_CRITICO,
    SERVICO_DE_PREVENCao,
    INSTALACAO_DE_ACESSORIOS,
    RETORNO_POS_SERVICO;
}

